{
 "title": "f2b",
 "tags": [ "favorites" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Unique IPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryText": "select * from banned",
     "rawQueryText": "select * from banned",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Unique Cities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(DISTINCT city) AS count\r\nFROM banned;",
     "rawQueryText": "SELECT COUNT(DISTINCT city) AS count\r\nFROM banned;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Unique Regions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(DISTINCT region) AS count\r\nFROM banned;",
     "rawQueryText": "SELECT COUNT(DISTINCT region) AS count\r\nFROM banned;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Unique Organizations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(DISTINCT organization) AS count\r\nFROM banned;",
     "rawQueryText": "SELECT COUNT(DISTINCT organization) AS count\r\nFROM banned;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Unique Countries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(DISTINCT country) AS count\r\nFROM banned;",
     "rawQueryText": "SELECT COUNT(DISTINCT country) AS count\r\nFROM banned;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "queryText": "SELECT country, COUNT(*) AS count\r\nFROM banned\r\nGROUP BY country;",
     "rawQueryText": "SELECT country, COUNT(*) AS count\r\nFROM banned\r\nGROUP BY country;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Bans by Country",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT country, COUNT(*) AS count\r\nFROM banned\r\nGROUP BY country\r\nORDER BY count desc",
     "rawQueryText": "SELECT country, COUNT(*) AS count\r\nFROM banned\r\nGROUP BY country\r\nORDER BY count desc",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Bans by Organization",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT organization, COUNT(*) AS count\r\nFROM banned\r\nGROUP BY organization\r\nORDER BY count desc",
     "rawQueryText": "SELECT organization, COUNT(*) AS count\r\nFROM banned\r\nGROUP BY organization\r\nORDER BY count desc",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "full table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "queryText": "select * from banned",
     "rawQueryText": "select * from banned",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}